apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  labels:
    app.kubernetes.io/instance: cert-manager-ingess-certs
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - api.q6bbt.dynamic.opentlc.com
      servingCertificate:
        name: custom-certs-managed
