apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rhacs-securedcluster-init-bundle
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-init-bundle-1
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: "2023-10-12T05:26:56.755125979Z"
                    init-bundle.stackrox.io/expires-at: "2024-10-11T05:27:00Z"
                    init-bundle.stackrox.io/id: ce15a51c-b259-4dc9-ae10-5903dca2f789
                    init-bundle.stackrox.io/name: cluster-init-bundle
                  creationTimestamp: null
                  name: admission-control-tls
                  namespace: rhacs-securedcluster
                stringData:
                  admission-control-cert.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
                  admission-control-key.pem: |
                    -----BEGIN EC PRIVATE KEY-----
                    -----END EC PRIVATE KEY-----
                  ca.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-init-bundle-2
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: "2023-10-12T05:26:56.755125979Z"
                    init-bundle.stackrox.io/expires-at: "2024-10-11T05:27:00Z"
                    init-bundle.stackrox.io/id: ce15a51c-b259-4dc9-ae10-5903dca2f789
                    init-bundle.stackrox.io/name: cluster-init-bundle
                  creationTimestamp: null
                  name: collector-tls
                  namespace: rhacs-securedcluster
                stringData:
                  ca.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
                  collector-cert.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
                  collector-key.pem: |
                    -----BEGIN EC PRIVATE KEY-----
                    -----END EC PRIVATE KEY-----
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-init-bundle-3
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: "2023-10-12T05:26:56.755125979Z"
                    init-bundle.stackrox.io/expires-at: "2024-10-11T05:27:00Z"
                    init-bundle.stackrox.io/id: ce15a51c-b259-4dc9-ae10-5903dca2f789
                    init-bundle.stackrox.io/name: cluster-init-bundle
                  creationTimestamp: null
                  name: sensor-tls
                  namespace: rhacs-securedcluster
                stringData:
                  ca.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
                  sensor-cert.pem: |
                    -----BEGIN CERTIFICATE-----
                    -----END CERTIFICATE-----
                  sensor-key.pem: |
                    -----BEGIN EC PRIVATE KEY-----
                    -----END EC PRIVATE KEY-----
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: enforce
          severity: high
  remediationAction: enforce