apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config: 
      bucket: acm-observability-bucket
      endpoint: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:443
      insecure: false
      access_key: C6N1FN98WU98GVBW8ELS
      secret_key: XD7hgjRAanWRklIDTlrnixZj2FrDLHdOI0Lglcjc
      http_config:
        insecure_skip_verify: true