apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: advanced-cluster-management-operatorgroup
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
