apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config: 
      bucket: acm-observability-bucket-6491814c-586a-4fdf-8c14-3af63cd2fbc4
      endpoint: s3.openshift-storage.svc:443
      insecure: false
      access_key: VIb09xNh9D7oMYKHizFY
      secret_key: qwhSVrxJhR11dQr1OqcFT72YLbN4GYUoEmRXJ1vB
      http_config:
        insecure_skip_verify: true