apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ca-policy
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: custom-ca
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: custom-ca
                  namespace: openshift-config
                data:
                  ca-bundle.crt: |
                    -----BEGIN CERTIFICATE-----
                    MIIDMzCCAhugAwIBAgIUHg4S6QcVPYav815xeJTVHZaxTyEwDQYJKoZIhvcNAQEL
                    BQAwKTEaMBgGA1UEAwwRc3BlbnNjb3QuZGRucy5uZXQxCzAJBgNVBAYTAkFVMB4X
                    DTI0MDUwNjIyMTYwOFoXDTI1MDQyNzIyMTYwOFowKTEaMBgGA1UEAwwRc3BlbnNj
                    b3QuZGRucy5uZXQxCzAJBgNVBAYTAkFVMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
                    MIIBCgKCAQEAwS8Z2RHoGKWyd6sOakNvBkSr6+7a4oOhaPOBecKwYEaONEZA9h3C
                    wN556puwkyicd6JrMxLcmTvgpjwdABcN6INY7LjejQ16CoMEUBquKizn42rNDn8C
                    qyZ9P8x/n7MrxG6Dzviiz9QczmVKmHiAp0Ehl1B/LpQnagCFocAl5/LAq+FmN//n
                    hiYulH7exOJwTCE/j+jTJ5lFAF8e/waeQ1krPi2xls9Jysfd/vzaWc57c/xtYQHz
                    1YFJ6MHx6kVJiFQWZqvmna1GC0uU/G+fPuijb21hB+F7weXk04JoRd19T76W8yV2
                    1cNZT3DKBhaoHduXKUUrMEfEOT8m3U2lEQIDAQABo1MwUTAdBgNVHQ4EFgQUI0Gz
                    +FxVZVfO6XK4JMFGD6MLFqUwHwYDVR0jBBgwFoAUI0Gz+FxVZVfO6XK4JMFGD6ML
                    FqUwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEATjzOctqxviZK
                    4k7iX461J2dljIVoDKWfrkHLfsD2xCMn8JxvoI+SeUFSgSBYwBtKN2zynAneMbt0
                    Op+Q2eiBZT+3nKba9Nl9nUnYZHAu6QOSyciaYLC+RUBbgk8TLsoBT/QmmBpD3uqz
                    sECHnsXtLtlgrt99fw8CYiH1+04oc2jGXgwVwBnMlEQPLnN/t2rmE/Z+1O4fUfID
                    Siqx9VuWHUKwHyiZCYq4p3hPesMwC40SH5UXUi2lhplwA5CGYnkkj4Av1PgAsvct
                    qqNkGfS6fFGuOMe5F6UdgyEJvAzQNH7Pk06c6C1jAxYRxi1rLHldyVI9q2peB4ph
                    9eXgl/RaXQ==
                    -----END CERTIFICATE-----
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: proxy-cluster
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Proxy
                metadata:
                  name: cluster
                spec:
                  trustedCA:
                    name: "custom-ca"
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: enforce
          severity: high


