apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: cluster
spec:
  servingCerts: 
    namedCertificates:
      - names: ["api.q6bbt.dynamic.opentlc.com"], 
        servingCertificate: 
          name: custom-certs-managed