apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: oauth-policyset
  namespace: rhacm-policies
spec:
  description: "Apply the OAuth config to clusters"
  policies:
    - oauth-policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oauth-placement-rule
  namespace: rhacm-policies
spec:
  clusterConditions: 
  - status: "True"
    type: ManagedClusterConditionAvailable  
  clusterSelector:
    matchExpressions:
      - key: name
        operator: Exists
