apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/openshift-pipelines-operator/overlays/latest
    repoURL: >-
      https://github.com/crscottau/openshift-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

