apiVersion: v1                    
kind: Namespace
metadata:
  name: rhacs-operator                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhacs
  namespace: rhacs-operator
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - rhacs
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: acm/acs
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rhacs
  name: rhacs-subscription-1
  namespace: rhacs-operator
spec:
  channel: ggithubcom-crscottau-openshift-gitops-ns/ggithubcom-crscottau-openshift-gitops
  placement:
    placementRef:
      kind: Placement
      name: rhacs-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: rhacs
  name: rhacs-placement-1
  namespace: rhacs-operator
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
  clusterSets:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: rhacs-operator
  name: default
spec:
  clusterSet: default

