apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: openshift-config
spec:
  commonName: api.name.domain
  dnsNames:
  - api.name.domain
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: custom-certs-managed