apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts: 
    namedCertificates:
      - names: 
          - api.q6bbt.dynamic.opentlc.com
        servingCertificate: 
          name: custom-certs-managed