apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResources=true"
  name: ca-issuer
spec:
  ca:
    secretName: ca-root-secret