apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  managementState: Managed
  rolloutStratgey: Recreate
  storage:
    pvc:
      claim: image-registry-storage-rwx
