apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage-rwx
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
#  storageClassName: thin
  storageClassName: ocs-storagecluster-cephfs
