apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: "2024-06-25T04:08:08Z"
  generation: 1
  name: default
  namespace: openshift-gitops
  resourceVersion: "41165"
  uid: 53812083-62de-44e8-bde1-63846487569a
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
