apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: odf-object-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephToolbox: {}
  mirroring: {}
  multiCloudGateway:
    dbStorageClassName: thin-csi
    #dbStorageClassName: gp3-csi
    reconcileStrategy: standalone
