---
- name: Change the cluster certificate
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # namespace for the CA configmap, also needs to be created in the LDAP sync ns
    ldap_namespace: openshift-config
  tasks:

# Nothing in here works
# ConfigMap fails as the include of the cert in the template fails
# Creating a secret only works once, subsequent attempts fail as it already exists
# Patch of the IngressController fails

    - name: Copy the CA cert into a local file
      ansible.builtin.copy:
        src: "{{ cert_ca_bundle_path }}"
        dest: working/ca.pem

    - name: Insert the leading spaces into the copied CA cert file
      ansible.builtin.replace:
        path: working/ca.pem    
        regexp: '^'  
        replace: '    '

    - name: Create the custom-ca ConfigMap
      ansible.builtin.template:
        src: ldap-custom-ca-configmap.yaml.j2
        dest: working/ldap-custom-ca-configmap.yaml

    - name: Apply the custom-ca ConfigMap
      kubernetes.core.k8s:
        state: present
        src: working/ldap-custom-ca-configmap.yaml

    - name: Update the cluster-wide proxy configuration with the new config map
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Proxy
          metadata:
            name: cluster
          spec:
            trustedCA:
              name: custom-ca

    - name: Create a secret that contains the wildcard certificate chain and key
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: secret
          metadata:
            name: "{{ cert_secret_name }}"
            namespace: openshift-ingress
          type: kubernetes.io/tls
          stringData:
            tls.key: "{{ lookup('ansible.builtin.file', cert_key_path) }}"
            tls.crt: "{{ lookup('ansible.builtin.file', cert_cert_path) }}"

    - name: Update the Ingress Controller configuration with the new secret
      kubernetes.core.k8s:
        state: present
        definition:
          kind: IngressController
          metadata:
            namespace: openshift-ingress-operator
            name: default
          spec:
            defaultCertificate:
              name: "{{ cert_secret_name }}"


