---
- name: Install and configure the compliance operator
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Ensure the working directory exists
      file:
        path: ./working
        state: directory

    - name: Create the {{ compliance_operator_namespace }} namespace
      ansible.builtin.k8s:
        name: "{{ compliance_operator_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Create the OperatorGroup
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: compliance-operator-group
            namespace: "{{ compliance_operator_namespace }}"
          spec:
            upgradeStrategy: Default

    - name: Create the Subscription
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: compliance-operator
            namespace: "{{ compliance_operator_namespace }}"
          spec:
            channel: stable
            installPlanApproval: Automatic
            name: compliance-operator
            source: "{{ redhat_operator_catalogue }}"
            sourceNamespace: openshift-marketplace

    - name: Wait for the Operator to install
      kubernetes.core.k8s_info:
        kind: Deployment
        wait: true
        name: compliance-operator
        namespace: "{{ compliance_operator_namespace }}"
        wait_sleep: 5
        wait_timeout: 150

    - name: Set the Subscription installPlan to manual
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: compliance-operator
            namespace: "{{ compliance_operator_namespace }}"
          spec:
            installPlanApproval: Manual
      
    - name: Create the ScanSettingBinding YAML
      ansible.builtin.template:
        src: compliance-scansettingbinding.yaml.j2
        dest: working/compliance-scansettingbinding.yaml

    - name: Apply the ScanSettingBinding YAML
      ansible.builtin.k8s:
        state: present
        src: working/compliance-scansettingbinding.yaml


  