---
- name: Encrypt the etcd database
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Apply the etcd database encryption
    kubernetes.core.k8s:
      state: present
      src: files/etcd-encryption.yaml
