---
- name: Configure LDAP RBAC
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Bind each LDAP group to the required cluster role
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: "{{ item.ocp_name }}_{{ item.ocp_role }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: "{{ item.ocp_role }}"
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: "{{ item.ocp_name }}"
      loop: "{{ ldap_group_list }}"
          