---
- name: Mirror registry pull 
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Generate the imageset-config.yaml
    ansible.builtin.template:
      src: imageset-config.yaml.j2
      dest: working/imageset-config.yaml

# This can take a while,
# Also not sure how to retain the metadata, if it even matters.
  - name: Pull the content (this can take a while)
    command: oc mirror --config=working/imageset-config.yaml file://./mirror

  - name: Extract the SHA256 sum of the release
    shell: |
      set -o pipefail
      oc adm release info {{ ocp_major_release }}.{{ ocp_minor_release }} | grep Pull\ From
    register: sha256

  - name: Display the SHA256 sum of the release
    debug: 
      msg: The SHA256 sum of the {{ ocp_major_release }}.{{ ocp_minor_release }} is {{ sha256.stdout.split(":")[2] }}
