---
- name: Mirror registry direct (pull and push)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Generate the imageset-config.yaml
    ansible.builtin.template:
      src: imageset-config.yaml.j2
      dest: working/imageset-config.yaml

# This can take a while,
# Also not sure how to retain the metadata, if it even matters.
  - name: Mirror the content (this can take a while)
    command: oc mirror --config=working/imageset-config.yaml docker://{{ mirror_registry_uri }}/{{ mirror_registry_path }}

  - name: Extract the SHA256 sum of the release
    shell: |
      set -o pipefail
      oc adm release info {{ mirror_ocp_major_release }}.{{ mirror_ocp_minor_release }} | grep Pull\ From
    register: sha256

  - name: Display the SHA256 sum of the release
    debug: 
      msg: The SHA256 sum of the {{ mirror_ocp_major_release }}.{{ mirror_ocp_minor_release }} is {{ sha256.stdout.split(":")[2] }}

  - name: Find the latest output directory
    shell: ls -td -- oc-mirror-workspace/* | head -n 1
    register: output_dir

  - name: Display the latest output directory
    debug:
      msg: Apply the YAML files to the cluster from the directory {{ output_dir.stdout }}