---
- name: Mirror registry push 
  hosts: localhost
  connection: local
  gather_facts: no
    
  # This can take a while,
  # Run as an asynchronous task
  - name: Push the content (this can take a while)
    command: oc mirror --from={{ mirror_archive_name }} docker://{{ mirror_registry_uri }}/{{ mirror_registry_path }}
    async: 3600
    poll: 0
    register: mirror_sleeper

  - name: Waiting up to 10 hours (3600 X 10s) for mirror job to complete
    ansible.builtin.async_status:
      jid: "{{ mirror_sleeper.ansible_job_id }}"
    register: mirror_result
    until: mirror_result.finished
    retries: 3600

  - name: Find the latest output directory
    shell: ls -td -- oc-mirror-workspace/* | head -n 1
    register: output_dir

  - name: Display the latest output directory
    debug:
      msg: Apply the YAML files to the cluster from the directory {{ output_dir.stdout }}