---
- name: Mirror registry pull 
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Generate the imageset-config.yaml
    ansible.builtin.template:
      src: imageset-config.yaml.j2
      dest: working/imageset-config.yaml

  # This can take a while,
  # Run as an asynchronous task
  - name: Pull the content (this can take a while)
    command: oc mirror --config=working/imageset-config.yaml file://./mirror
    async: 3600
    poll: 0
    register: mirror_sleeper

  - name: Waiting up to 10 hours (3600 X 10s) for mirror job to complete
    ansible.builtin.async_status:
      jid: "{{ mirror_sleeper.ansible_job_id }}"
    register: mirror_result
    until: mirror_result.finished
    retries: 3600

  - name: Extract the SHA256 sum of the release
    shell: |
      set -o pipefail
      oc adm release info {{ ocp_major_release }}.{{ ocp_minor_release }} | grep Pull\ From
    register: sha256

  - name: Display the SHA256 sum of the release
    debug: 
      msg: The SHA256 sum of the {{ ocp_major_release }}.{{ ocp_minor_release }} is {{ sha256.stdout.split(":")[2] }}
