---
- name: Mirror registry direct (pull and push)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Ensure the working directory exists
    file:
      path: ./working
      state: directory
        
  - name: Generate the imageset-config.yaml
    ansible.builtin.template:
      src: imageset-config.yaml.j2
      dest: working/imageset-config.yaml

  # This can take a while,
  # Run as an asynchronous task
  - name: Mirror the content (this can take a while)
    ansible.builtin.command: oc mirror --config=working/imageset-config.yaml docker://{{ mirror_registry_uri }}/{{ mirror_registry_path }}
    async: 36000
    poll: 0
    register: mirror_sleeper

  - name: Waiting up to 10 hours (3600 X 10s) for mirror job to complete
    ansible.builtin.async_status:
      jid: "{{ mirror_sleeper.ansible_job_id }}"
    register: mirror_result
    until: mirror_result.finished
    retries: 3600

  - name: Extract the SHA256 sum of the release
    ansible.builtin.shell: |
      set -o pipefail
      oc adm release info {{ mirror_ocp_major_release }}.{{ mirror_ocp_minor_release }} | grep Pull\ From
    register: sha256

  - name: Display the SHA256 sum of the release
    ansible.builtin.debug: 
      msg: The SHA256 sum of the {{ mirror_ocp_major_release }}.{{ mirror_ocp_minor_release }} is {{ sha256.stdout.split(":")[2] }}

  - name: Find the latest output directory
    ansible.builtin.shell: ls -td -- oc-mirror-workspace/* | head -n 1
    register: output_dir

  - name: Display the latest output directory
    ansible.builtin.debug:
      msg: Apply the YAML files to the cluster from the directory {{ output_dir.stdout }}