---
- name: Install and configure the OADP operator
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Ensure the working directory exists
      file:
        path: ./working
        state: directory

    - name: Create the {{ oadp_namespace }} namespace
      ansible.builtin.k8s:
        name: "{{ oadp_namespac }}"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Create the OperatorGroup
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: oadp-operator-group
            namespace: "{{ oadp_namespac }}"
          spec:
            targetNamespaces:
            - "{{ oadp_namespac }}"
            upgradeStrategy: Default

    - name: Create the Subscription
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: oadp-operator
            namespace: "{{ oadp_namespac }}"
          spec:
            channel: stable-1.3
            installPlanApproval: Automatic
            name: redhat-oadp-operator
            source: "{{ redhat_operator_catalogue }}"
            sourceNamespace: openshift-marketplace

    - name: Wait for the Operator to install
      kubernetes.core.k8s_info:
        kind: Deployment
        wait: true
        name: openshift-adp-controller-manager
        namespace: "{{ oadp_namespac }}"
        wait_sleep: 5
        wait_timeout: 150

    - name: Set the Subscription installPlan to manual
      ansible.builtin.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: redhat-oadp-operator
            namespace: "{{ oadp_namespac }}"
          spec:
            installPlanApproval: Manual
      
