apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: openshift-ingress
spec:
  commonName: kubernetes
  dnsNames:
  - 'console-openshift-console.apps.54fm9.dynamic.opentlc.com'
  - 'oauth-openshift.apps.54fm9.dynamic.opentlc.com'
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: custom-certs-managed