apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: multiclusterhub
  namespace: advanced-cluster-management
spec: {}